### ISSUE TITLE
Fix agencies index view

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#694]
This page was not intended to be visible initially.  We can remove it or make or functional.

**Comment by trystant** [comment]
What does 'make it functional' mean?

**Comment by campgurus** [comment]
some fixes to make this presentable are on production

**Comment by trystant** [comment]
In line with this & other changes, what was fixed in this ticket?

On Mon, Jul 11, 2016 at 1:24 AM, campgurus <notifications@github.com> wrote:

> some fixes to make this presentable are on production
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/BOWiki/BOW/issues/694#issuecomment-231644801>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA0xXhljbgWmhQvUGMVTREn0VB2dmRzks5qUdOrgaJpZM4JItWw>
> .
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
the agencies page didn't have the names of agencies and included links to destroy agencies (required authentication, but still not ok).  added some css as well.
